// query
export const QUERY_KEY_MAJOR_VERSION = 'v';

// cookies
export const COOKIE_KEY_MAJOR_VERSION = 'COOKIE_KEY_MAJOR_VERSION';
export const COOKIE_KEY_MAJOR_VERSION_ID = 'COOKIE_KEY_MAJOR_VERSION_ID';
