import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import './layout.scss'

export default function RootLayout({
  children
}: {
  children: React.ReactNode,

}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>公共头部
          <Link href="/docs/button/api">文档界面</Link>
          <Link href="/admin/account">管理界面</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
